---
title: "BIOL708 Data Visualization"
format: html
editor: visual
---

## Practicing Data Visualization 

```{r}
install.packages('here')
library(here)
library(tidyverse)
library(readr)
```

## Loading Data & Viewing Data

```{#Load National Park Data from OHI workshop}

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```

Using Data Plots

```{r}
#Make some plots

#to make a plot 
ggplot(ca) +geom_point(aes(x=year,y=visitors, color=park_name))

#to make a plot with color and a title 
ggplot(ca) +geom_point(aes(x=year,y=visitors,color=park_name)) + labs(y='visitation', title='National park visitors')

#another plot
ggplot(ca) +geom_point(aes(x=year,y=visitors,color=park_name)) + labs(y='visitation', title='National park visitors')+theme_minimal() +theme(legend.title = element_blank())

#create a new plot for SE parks showing scatterplot of visitors to each park per state 
ggplot(se)+ geom_point(aes(x=year,y=visitors, color=state))+labs(y='visitation')

ggplot(se)+ geom_point(aes(x=year,y=visitors, color=state))+labs(y='visitation', title='Southeast United States National Park Visitors')

#making a box plot for se parks
ggplot(se)+geom_boxplot(aes(x=park_name, y=visitors))

#making plots per state
ggplot(se)+geom_boxplot(aes(x=park_name, y=visitors))+facet_wrap(~state)

#making plots with different scale
ggplot(se)+geom_boxplot(aes(x=park_name, y=visitors))+facet_wrap(~state, scales='free')

#show a line for visitors at se parks over time
ggplot(se)+ geom_line(aes(x=year,y=vistors, color=park_name))

```
